[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "postgresql"]

[phases.install]
cmds = ["pip install --no-cache-dir --break-system-packages -r requirements.txt"]

[start]
cmd = "python -m app.main"
